-i
-classdir ..\bin
-applet 0xA0:0x00:0x00:0x00:0x62:0x03:0x01:0x0C:0x01:0x01 com.consec.iotsafe.IoTSafeApplet
-out CAP
-d ..\deliverables\IoTSafeApplet
-v
-debug
-target 3.1.0
com.consec.iotsafe
0xA0:0x00:0x00:0x00:0x62:0x03:0x01:0x0C:0x01 1.0