# Configuration file to SmartCard TestTool

# protocol used in SCardConnect : T0 T1 T0T1 or 0
connect-protocol=0

# protocol used in SCardTransmit : T0 T1 or RAW
transmit-protocol=T1

# if set additionally call SCardControl(IOCTL_SMARTCARD_SET_PROTOCOL) after SCardConnect with provided value in hex
# 01 for T0 and 02 for T1
control-protocol=01

# mode used in SCardConnect : 'shared' 'direct' 'exclusive' 
mode=direct

device=Alcorlink USB Smart Card Reader 0